
MOTOR_BACK_LEFT_MINUS = 9
MOTOR_BACK_LEFT_PLUS = 10
MOTOR_BACK_RIGHT_MINUS = 11
MOTOR_BACK_RIGHT_PLUS = 25
MOTOR_FRONT_LEFT_MINUS = 22
MOTOR_FRONT_LEFT_PLUS = 27
MOTOR_FRONT_RIGHT_MINUS = 24
MOTOR_FRONT_RIGHT_PLUS = 23
PWM_DRIVE = 8

SWITCH_LIFT = 19 

PWM_LIFT = 26

LIFT_PLUS = 20
LIFT_MINUS = 21