
MOTOR_BACK_LEFT_MINUS = 21
MOTOR_BACK_LEFT_PLUS = 19
MOTOR_BACK_RIGHT_MINUS = 23
MOTOR_BACK_RIGHT_PLUS = 22
MOTOR_FRONT_LEFT_MINUS = 11
MOTOR_FRONT_LEFT_PLUS = 13
MOTOR_FRONT_RIGHT_MINUS = 18
MOTOR_FRONT_RIGHT_PLUS = 16
PWM_DRIVE = 24

