
MOTOR_BACK_LEFT_MINUS = 9 
MOTOR_BACK_LEFT_PLUS = 10 
MOTOR_BACK_RIGHT_MINUS = 11 
MOTOR_BACK_RIGHT_PLUS = 25 
MOTOR_FRONT_LEFT_MINUS = 22 
MOTOR_FRONT_LEFT_PLUS = 27 
MOTOR_FRONT_RIGHT_MINUS = 24 
MOTOR_FRONT_RIGHT_PLUS = 23 
PWM_DRIVE = 8 

SENSOR_TIGGER = 15 
SENSOR_FRONT_LEFT = 4 
SENSOR_FRONT_RIGHT = 14 
SENSOR_SIDE_LEFT = 17 
SENSOR_SIDE_RIGHT = 18

SWITCH_FRONT_LEFT = 2 
SWITCH_FRONT_RIGHT = 3 
SWITCH_START = 7 
SWITCH_LIFT_UP = 19  
SWITCH_LIFT_DOWN = 16

PWM_LIFT = 26  
LIFT_PLUS = 20 
LIFT_MINUS = 21
  
LED_A = 6 
LED_B = 12 
LED_C = 13